In [1]:
import numpy as np
softmax_output = [0.7,0.1,0.2]
softmax_output = np.array(softmax_output).reshape(-1,1)
print(softmax_output)


[[0.7]
 [0.1]
 [0.2]]


In [2]:
softmax_output.shape[0]

3

In [5]:
print(softmax_output.T)

[[0.7 0.1 0.2]]


In [4]:
print(np.dot(softmax_output, softmax_output.T))

[[0.49 0.07 0.14]
 [0.07 0.01 0.02]
 [0.14 0.02 0.04]]


In [8]:
dvalues1 =[1,2,3,4]
dvalues2  = [[1,2,3,4],[5,6,7,8]]

dinputs = np.empty_like(dvalues1)
print(dinputs)

[              0 562958543355906 105553942365509               0]
